language: node_js

addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern
    - fontconfig

before_script:
  - npm install google-font-installer
  - gfi install merriweather

script: (cd $TRAVIS_BUILD_DIR/build; ./convert2pdf.sh)
