addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern
    - fontconfig

before_script:
  - mkdir ~/.fonts
  - cd ~/.fonts && wget https://github.com/google/fonts/archive/master.zip && unzip master.zip
  - fc-cache -fv

script: (cd $TRAVIS_BUILD_DIR/build; ./convert2pdf.sh)
