addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern

before_script:
  - cd && wget https://raw.githubusercontent.com/hotice/webupd8/master/install-google-fonts
  - chmod +x install-google-fonts
  - ./install-google-fonts

script: (cd $TRAVIS_BUILD_DIR/build; ./convert2pdf.sh)
