language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern
    - fontconfig

before_script:
  - npm install git+ssh://git@github.com/asbjornu/google-font-installer.git
  - gfi download "Merriweather"
  - gfi install "Merriweather"
  - gfi download "Open Sans"
  - gfi install "Open Sans"

script: (cd $TRAVIS_BUILD_DIR/build; ./convert2pdf.sh)
