language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern
    - fontconfig

before_script:
  - mkdir $TRAVIS_BUILD_DIR/fonts
  - npm install https://github.com/asbjornu/google-font-installer.git
  - gfi download "Merriweather" -d $TRAVIS_BUILD_DIR/fonts/
  - gfi install "Merriweather"
  - gfi download "Open Sans" -d $TRAVIS_BUILD_DIR/fonts/
  - gfi install "Open Sans"

script:
  - pandoc -N                                   \
           --template=./piratpartiet.tex        \
           --variable mainfont="Merriweather"   \
           --variable sansfont="OpenSans"       \
           --variable monofont="FreeMono"       \
           --variable fontsize=8pt              \
           --variable version=201708            \
           valgprogram.md                       \
           --latex-engine=xelatex               \
           --toc                                \
           -o valgprogram.pdf
  - pandoc -N --template=./piratpartiet.tex --variable mainfont="Merriweather" --variable sansfont="OpenSans" --variable monofont="FreeMono" --variable fontsize=8pt --variable version=201708 faq.md --latex-engine=xelatex --toc -o faq.pdf
  - pandoc -N --template=./piratpartiet.tex --variable mainfont="Merriweather" --variable sansfont="OpenSans" --variable monofont="FreeMono" --variable fontsize=17pt --variable version=201708 valgprogram.md --latex-engine=xelatex --toc -o valgprogram-stor.pdf
  - pandoc -N --template=./piratpartiet.tex --variable mainfont="Merriweather" --variable sansfont="OpenSans" --variable monofont="FreeMono" --variable fontsize=17pt --variable version=201708 faq.md --latex-engine=xelatex --toc -o faq-stor.pdf
