addons:
  apt:
    packages:
    - pandoc
    - texlive-xetex

before_script:
  - cd && wget https://raw.githubusercontent.com/hotice/webupd8/master/install-google-fonts
  - chmod +x install-google-fonts
  - ./install-google-fonts

script:
  - cd ./build
  - ./convert2pdf.sh
