language: node_js
node_js:
  - "6"

addons:
  apt:
    packages:
    - pandoc
    - texlive-full
    - lmodern
    - fontconfig

before_script:
  - mkdir $TRAVIS_BUILD_DIR/fonts
  - npm install https://github.com/asbjornu/google-font-installer.git
  - gfi download "Merriweather" -d $TRAVIS_BUILD_DIR/fonts/
  - gfi install "Merriweather"
  - gfi download "Open Sans" -d $TRAVIS_BUILD_DIR/fonts/
  - gfi install "Open Sans"

script: (cd $TRAVIS_BUILD_DIR/build; ./convert2pdf.sh)
